name: 'WordPress Plugin Build Zip'
description: 'Build a release zip of a WordPress Plugin'
author: 'byteperfect.dev'
inputs:
  host:
    description: 'SSH host'
    required: true
  username:
    description: 'SSH username'
    required: true
  password:
    description: 'SSH password'
    required: true
  path:
    description: 'SSH path'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build plugin
      run: if test -f composer.json; then composer install --no-dev; fi;
      shell: bash

    - name: Generate zip archive
      id: archive
      run: ${{ github.action_path }}/build-zip.sh
      shell: bash

    - name: Copy file via SSH
      uses: ilCollez/ssh-scp-deploy@v1.2.0
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        files: ${{ github.event.repository.name }}.zip
        remote-path: ${{ inputs.path }}
